[project]
name = "coconuts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "placo>=0.9.20",
    "pyqt5>=5.15.11",
    "python-can[canalystii]>=4.6.1",
]
